import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Noto_Serif_Display } from "next/font/google";
import { Lexend } from "next/font/google";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const notoSerifDisplay = Noto_Serif_Display({
  subsets: ["latin"],
  weight: ["500"],
  variable: "--font-noto-serif-display",
  display: "swap",
});

const lexend = Lexend({
  subsets: ["latin"],
  weight: ["500"],
  variable: "--font-lexend",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${notoSerifDisplay.variable} ${notoSerifDisplay.variable} ${lexend.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
